---
# tasks file for vault
- include_tasks: variables.yml
- include_tasks: asserts.yml

- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
- include_tasks: arch.yml
  when: ansible_distribution == "Archlinux"

- include_tasks: configure.yml

- name: Create unseal directories
  file:
    path: "{{ _hvault_keys_dir }}/{{ inventory_hostname }}"
    state: directory
    owner: root
    group: root
    mode: "0700"
  delegate_to: localhost

- name: Create root key directories
  file:
    path: "{{ _hvault_token_dir }}/{{ inventory_hostname }}"
    state: directory
    owner: root
    group: root
    mode: "0700"
  delegate_to: localhost

- name: Initialise Vault operator
  shell: vault operator init -key-shares=5 -key-threshold=3 -format json
  environment:
    VAULT_ADDR: "http://127.0.0.1:8200"
  register: vault_init_results

- name: Parse output of vault init
  set_fact:
    vault_init_parsed: "{{ vault_init_results.stdout | from_json }}"
  no_log: true

- name: Write unseal keys to files
  copy:
    dest: "{{ _hvault_keys_dir }}/{{ inventory_hostname }}/unseal_key_{{ item.0 }}"
    content: "{{ item.1 }}"
    owner: root
    group: root
    mode: "0600"
  with_indexed_items: "{{ vault_init_parsed.unseal_keys_hex }}"
  delegate_to: localhost
  no_log: true

- name: Write root token to file
  copy:
    content: "{{ vault_init_parsed.root_token }}"
    dest: "{{ _hvault_token_dir}}/{{ inventory_hostname }}/rootkey"
    owner: root
    group: root
    mode: "0600"
  delegate_to: localhost
  no_log: true
